---
- name: Read and Process CSV File on Localhost
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    csv_file_path: "test7.csv"  # Update this to your actual CSV file path

  tasks:
    - name: Check if CSV file exists
      stat:
        path: "{{ csv_file_path }}"
      register: csv_file_stat

    - name: Fail if CSV file doesn't exist
      fail:
        msg: "CSV file not found at {{ csv_file_path }}"
      when: not csv_file_stat.stat.exists

    - name: Read CSV file
      community.general.read_csv:
        path: "{{ csv_file_path }}"
        delimiter: ","
      register: csv_data

    - name: Convert IP string and Port string to lists
      set_fact:
        processed_data: "{{ processed_data | default([]) + 
          [item | combine({
            'dst_ip': (item['dst_ip'] | default('')).splitlines() | map('trim') | list,
            'TCP': item['TCP'] | default('') | split(', ') | map('split', '/') | list
          })] }}"
      loop: "{{ csv_data.list }}"

    - name: Debug - Display processed data
      debug:
        msg: "{{ processed_data }}"

    - name: Process each row with structured data
      debug:
        msg: >-
          Processing Entry:
          Source: {{ item.src_ip }} ({{ item.SRC }})
          Destination: {{ item.dst_ip }} ({{ item.DST }})
          Allowed TCP Ports: {{ item.TCP }}
          UDP: {{ item.UDP }}
          ICMP Allowed: {{ item.ICMP }}
          Objective: {{ item.Objective }}
          Remark: {{ item.Remark }}
      loop: "{{ processed_data }}"


